#!/bin/sh

CWD="`pwd`"
WIRINGS=$CWD/modules.properties
PORT=8181

export JAVA_OPTIONS="-Xms16M -Xmx64M"
export BUTTERFLY_WIRINGS="$WIRINGS"
export BUTTERFLY_MODULES_PATH="$CWD/modules/"
export BUTTERFLY_PROPERTIES="$CWD/butterfly.properties"

eval ../butterfly/butterfly -p $PORT run
